package uids

import (
	"encoding/json"
	"io"
	"log"
	"net/http"
	"time"
)

type AutoGenerated []struct {
	ID         int       `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	ScreenName string    `json:"screen_name"`
	UID        string    `json:"uid"`
	Status     bool      `json:"status"`
}

func GetUids() AutoGenerated {
	url := "https://weibo.julai.fun/api/config?query=read"

	// 创建一个HTTP客户端
	client := &http.Client{}

	// 创建HTTP请求
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Fatalf("Failed to create HTTP request: %v", err)
	}

	// 发送HTTP请求
	resp, err := client.Do(req)
	if err != nil {
		log.Printf("Failed to send HTTP request: %v", err)
		return nil
	}
	defer resp.Body.Close()

	// 读取响应体
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Printf("Failed to read response body: %v", err)
		return nil
	}

	// 解析JSON数据
	var uids AutoGenerated
	if err := json.Unmarshal(data, &uids); err != nil {
		log.Printf("Failed to unmarshal JSON response: %v", err)
		return nil
	}

	return uids
}
